### ISSUE TITLE
AppCenter Review: Please use default settings

### ISSUE THREAD

**Issue by danrabbit** [eugeneia/recall#8]
Thanks for your app submission! I've marked the latest release as "Needs Fixing" because screenshots do not seem to show elementary default settings, specifically with regards to window controls.

Screenshots in AppCenter must show elementary OS default settings so that users get what they see in the store. See our [publishing guide](https://github.com/elementary/houston/wiki/Before-You-Publish#appdata-and-oars) for more information

**Comment by eugeneia** [comment]
Fixed in https://github.com/eugeneia/recall/commit/bb7a48a3af9b8dd61bfb8a0ba5b710cd97b38c51
